title: Minimal theme
logo:
description: 666
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
repository: glacheysist/glacheysist.github.io
github_url: https://glacheysist/github_username
url: https://glacheysist.github.io
